spring.application.name=usuario
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url= 
spring.datasource.username=
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# JWT
jwt.secret.key=AAy5AS4sRVkcgnXb9BPmqFG7F4dTFFcJphxCGIc4qsg
jwt.expiration="3600000"
jwt.refresh-expiration="604800000"